# Generated by Django 5.2.10 on 2026-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogging',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
